### PR TITLE
Metadata GDSC annotation improvements

### PR DESCRIPTION
**Pull request by Lilly-May**
**Description of changes**

- Fixed the logger error message in the cell line metadata annotation. The code will still fail, but now the informative logging message will be shown.
- The parameter specifying the GDSC dataset can now also be provided as a string. Feel free to reject this change, as I might be the only user making the mistake of providing it as a string instead of an integer. The latter causes the method to always use GDSC dataset 2 without specifically stating it, which might be overlooked by the user. I also added a test that the parameter is set to `1` or `2` and otherwise throw an error.
- The most important change is in the `annotate_from_gdsc` method, which now uses the correct GDSC data to compute. Previously, the code would fail for me if GDSC2 was used.
- Adapted the `Statsmodel` example. I believe an old class name might have been used here. It's still not a working example as the `adata` is not defined, but I think it is much easier for users to understand now.

### CODE REVIEW

**Review by Zethson — APPROVED** [review]
Thank you! The GDSC string change is fine with me. I would also even argue that it should be a `Literal` or the two string options @wxicu ?

**Review by wxicu — APPROVED** [review]
Thanks for the improvement! `Literal` of gdsc dataset sounds good to me

**Comment by Zethson** [comment]
@Lilly-May can you change this so that we use string literals for the dataset names? Maybe `Literal["gdsc_1", "gdsc_2"]` or something of that sort? Then we can merge it

**Comment by Lilly-May** [comment]
Sure! But you still want it to work with integers as well, right? So something like `Literal["gdsc_1", "gdsc_2"] | Literal[1, 2]`?

**Pull request merged**
